In [22]:
import numpy as np
np.random.seed(1)

In [23]:
def relu(x):
    return (x>0)*x

def relu2deriv(output):
    return output>0

alpha = 0.1
hidden_size = 4

In [24]:
streetlights = np.array( [  [ 1, 0, 1 ],
                            [ 0, 1, 1 ],
                            [ 0, 0, 1 ],
                            [ 1, 1, 1 ] ] )
streetlights

array([[1, 0, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 1, 1]])

In [25]:
walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T
walk_vs_stop

array([[1],
       [1],
       [0],
       [0]])

In [26]:
weights_0_1 = 2*np.random.random((3, hidden_size))-1
weights_1_2 = 2*np.random.random((hidden_size, 1))-1

In [27]:
layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = relu(np.dot(layer_1, weights_1_2))

In [32]:
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights)):
        layer_0 = streetlights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)


        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1])**2)
        layer_2_delta = (walk_vs_stop[i:i+1] - layer_2)
        layer_1_delta = np.dot(layer_2_delta, weights_1_2.T)*relu2deriv(layer_1)

        weights_1_2 += alpha*np.dot(layer_1.T, layer_2_delta)
        weights_0_1 += alpha*np.dot(layer_0.T, layer_1_delta)

    if(iteration % 10 == 9):
        print("Error:" + str(layer_2_error))



Error:0.7508568248451376
Error:0.5419725893582122
Error:0.45245811639182343
Error:0.31328400775211834
Error:0.17946259471544115
Error:0.08081748098257939


In [33]:
walk_vs_stop[i]

array([0])

In [34]:
walk_vs_stop[i:i+1]

array([[0]])

In [35]:
# Training the MNIST on 3 layer network

In [36]:
import sys, numpy as np
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
images, labels = (x_train[0:1000].reshape(1000,28*28)/255, y_train[0:1000])
one_hot_labels = np.zeros((len(labels),10))

for i,l in enumerate(labels):
    one_hot_labels[i][l] = 1
labels = one_hot_labels

test_images = x_test.reshape(len(x_test),28*28) / 255
test_labels = np.zeros((len(y_test),10))
for i,l in enumerate(y_test):
    test_labels[i][l] = 1

np.random.seed(1)
relu = lambda x:(x>=0) * x
relu2deriv = lambda x: x>=0

alpha, iterations, hidden_size, pixels_per_image, num_labels = (0.005, 350, 40, 784, 10)


weights_0_1 = 0.2*np.random.random((pixels_per_image,hidden_size)) - 0.1
weights_1_2 = 0.2*np.random.random((hidden_size,num_labels)) - 0.1


for j in range(iterations):
    error, correct_cnt = (0.0, 0)
    for i in range(len(images)):
        layer_0 = images[i:i+1]
        layer_1 = relu(np.dot(layer_0,weights_0_1))
        layer_2 = np.dot(layer_1,weights_1_2)

        error += np.sum((labels[i:i+1] - layer_2) ** 2)

        #To calculate the accuracy
        correct_cnt += int(np.argmax(layer_2) == np.argmax(labels[i:i+1]))

        layer_2_delta = (labels[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T)* relu2deriv(layer_1)

        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)

    sys.stdout.write("\r"+ \
    " I:"+str(j)+ \
    " Error:" + str(error/float(len(images)))[0:5] +\
    " Correct:" + str(correct_cnt/float(len(images))))

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2
 I:349 Error:0.108 Correct:1.0

In [37]:
# Testing on Test data

if(j % 10 == 0 or j == iterations-1):
    error, correct_cnt = (0.0, 0)

for i in range(len(test_images)):
    layer_0 = test_images[i:i+1]
    layer_1 = relu(np.dot(layer_0,weights_0_1))
    layer_2 = np.dot(layer_1,weights_1_2)

    error += np.sum((test_labels[i:i+1] - layer_2) ** 2)
    correct_cnt += int(np.argmax(layer_2) == np.argmax(test_labels[i:i+1]))
    
sys.stdout.write(" Test-Err:" + str(error/float(len(test_images)))[0:5] +\
" Test-Acc:" + str(correct_cnt/float(len(test_images))))
print()

 Test-Err:0.653 Test-Acc:0.7073
